### ISSUE TITLE
Reexport @relation

### ISSUE THREAD

**Issue by GeorgeR227** [AlgebraicJulia/DiagrammaticEquations.jl#43]
Even though DiagrammaticEquations exports its own composition code, like `oapply`, it does not currently reexport the `@relation` macro that downstream packages would need to actually compose. As of now, a user would have to add Catlab separately to have this work, which is not at all clear. However, DiagrammaticEquations already requires Catlab to function so reexporting `@relation` can be done at no cost.

**Comment by lukem12345** [comment]
Would updating documentation also close this?

**Comment by GeorgeR227** [comment]
I would say that since `@relation`, plus `apex` as I've found, is required to use the composition code here, the best solution is to just reexport it. I already have a branch set up.
