### ISSUE TITLE
Bad typing for Decapodes

### ISSUE THREAD

**Issue by GeorgeR227** [AlgebraicJulia/DiagrammaticEquations.jl#46]
This bug seems to have been introduced in version 0.1.5 and is causing the Decapodes documentation to break. Below is the error caused.
```julia
Error: failed to run `@example` block in src/ice_dynamics/ice_dynamics.md:200-203
│ ```@example DEC
│ sim = eval(gensim(ice_dynamics1D, dimension=1))
│ fₘ = sim(sd, generate)
│ ```
│   exception =
│    ArgumentError: cannot parse "dynamics_•2" as Float64
```

I've confirmed this is due to 0.1.5 since I've bumped the version back down to 0.1.4 and the same page built fine. This will be resolved once the issue is found and tests are added to prevent this issue again.

**Comment by lukem12345** [comment]
I suspect it is because types are inferred in order of precedence as given in the type inference rules list. This has come up before. Adding a new operator to the list changes that order.

**Comment by lukem12345** [comment]
So, a rule which infers literals would be a likely cause.

**Comment by lukem12345** [comment]
So, a rule which infers literals would be a likely cause.

Due to the 2 out of 3 logic for matching, lines like this one can cause trouble:

```julia
  (proj1_type = :Literal, proj2_type = :Form1, res_type = :Form1, op_names = [:/, :./, :*, :.*, :^, :.^]),
```

**Comment by lukem12345** [comment]
So, a rule which infers literals would be a likely cause.

Due to the 2 out of 3 logic for matching, lines like this one can cause trouble:

```julia
  (proj1_type = :Literal, proj2_type = :Form1, res_type = :Form1, op_names = [:/, :./, :*, :.*, :^, :.^]),
```

This line that just checks whether 2 out of 3 are `:infer` should be amended. Literals have to have special treatment.
https://github.com/AlgebraicJulia/DiagrammaticEquations.jl/blob/main/src%2Facset.jl#L412

**Comment by GeorgeR227** [comment]
Yeah, looking at the Decapode itself, the `dynamics_•2` in question is the result of an `avg_01`, which is then the source of a `*`. I'm seeing now this issue didn't actually appear in this version was was uncovered instead.

<img width="384" alt="image" src="https://github.com/AlgebraicJulia/DiagrammaticEquations.jl/assets/78235421/bf3fea9c-bb16-4469-9733-013108bf82fb">

This voting logic seems to be coming back to bite us again and again.

**Comment by lukem12345** [comment]
Bug not introduced in 0.1.5 AFAICT.

**Comment by lukem12345** [comment]
Yeah. One option is to silo rules for Literals into a new list, and perform a different check for those.

**Comment by GeorgeR227** [comment]
The inferred version. 

<img width="383" alt="image" src="https://github.com/AlgebraicJulia/DiagrammaticEquations.jl/assets/78235421/9bd41c1a-e907-4667-9ade-85b2fd205537">

I'm going to make a post a MWE based off this.
