### ISSUE TITLE
Upload jobscript.sh

### ISSUE THREAD

**Issue by lukem12345** [AlgebraicJulia/DiagrammaticEquations.jl#78]
The "Build docs" action in `.buildkit/pipeline.yml`, which runs tests and builds docs calls out to a script `jobscript.sh`. However, this script `jobscript.sh` is missing from the `.buildkite`folder in this repo.

There is a `jobscript.sh` given in the AlgebraicTemplate:
https://github.com/AlgebraicJulia/AlgebraicTemplate.jl/blob/main/.buildkite/jobscript.sh

There is an instantiation of `jobscript.sh` somewhere, since a copy of it is executed when the actions are run, but I cannot locate it. @quffaro can you upload the appropriate jobscript file and ensure that that jobscript (from this repo) is the one getting called? Or is the installation of this file supposed to be manual for some reason?

**Comment by quffaro** [comment]
This issue is resolved by [PR 79](https://github.com/AlgebraicJulia/DiagrammaticEquations.jl/pull/79) which places the script in the correct location, as well as dynamizes the pipeline.

**Comment by quffaro** [comment]
Marking as closed

**Comment by lukem12345** [comment]
Which jobscript was getting run before?

**Comment by quffaro** [comment]
The jobscript was in the parent directory, `DiagrammaticEquations.jl/jobscriph.sh`. The `pipeline.yml` was calling `jobscript.sh`, not `buildkite/jobscript.sh`, so as part of this I moved the script into the buildkite directory and changed the path to point to the latter.
